### ISSUE TITLE
Mouse Stuck on Screen

### ISSUE THREAD

**Issue by ReZZe34** [Project-India/Pi-inventory#1]
I close the inventory and then I see my character and I still have the mouse that you use in the inventory

**Comment by Pavan576** [comment]
>
did you changed any files in inventory

**Comment by FM-Dev-Macke** [comment]
I have that problem too, And i didnt change anything

**Comment by madhuvamsii** [comment]
did you change the name of inventory to qb-inventory

**Comment by zeemkarry** [comment]
the script needs to be updated to the latest build of qbcore framework.

**Comment by GabbarFramework** [comment]
Fixed
